name: Build and deploy Python app to Azure Web App - asksphere-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip . -r -x "venv/*" "__pycache__/*" "*.pyc" "*.pyo" "*.pyd" "*.log" "*.tar.gz" "*.zip" ".env" ".git/*" ".github/*" "*.model" "*.cache"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Stop App Service'
        run: |
          az webapp stop \
            --resource-group asksphere-resource-group \
            --name asksphere-backend

      - name: 'Get Publishing Credentials'
        id: get-creds
        run: |
          creds=$(az webapp deployment user show --query "{username:publishingUserName,password:publishingPassword}" -o json)
          echo "PUBLISH_USER=$(echo $creds | jq -r .username)" >> $GITHUB_ENV
          echo "PUBLISH_PASS=$(echo $creds | jq -r .password)" >> $GITHUB_ENV

      - name: 'Clear /site/wwwroot using Kudu API'
        run: |
          curl -X DELETE -u "${{ env.PUBLISH_USER }}:${{ env.PUBLISH_PASS }}" \
            https://asksphere-backend-f3bccbc7d6euc6gf.scm.australiacentral-01.azurewebsites.net/api/vfs/site/wwwroot/ \
            --header "If-Match: *"

      - name: 'Deploy to Azure Web App using Azure CLI'
        run: |
          az webapp deployment source config-zip \
            --resource-group asksphere-resource-group \
            --name asksphere-backend \
            --src release.zip

      - name: 'Start App Service'
        run: |
          az webapp start \
            --resource-group asksphere-resource-group \
            --name asksphere-backend